# -*- coding: utf-8 -*-
"""context_embedding_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3BlsmMK7XyyPzWtNWiNsGKsbCi5nezD

# Context Embedding Test (without fine-tuning)

Tests query embedding strategies from `Reference.md` against the `rag_disease` FAISS+SQLite index:

| Strategy | Reference.md | Description |
|---|---|---|
| **Baseline** | — | embed `term` only (current behaviour) |
| **Method 1** (Concat) | §1 Prompt Engineering | embed `"term -> relevant_context_fields"` |
| **Method 2** (Token Extraction) | §2 Contextualized Token Extraction | average hidden states at `term` token positions |
| **Method 3** (Hybrid) | §3 Hybrid Embedding | `(embed(term) + embed(context)) / 2` |

**Notes**:
- Methods 1 & 3 query the existing `rag_pubmed_bert_disease.index` (mean-pooled ST embeddings, full 13 927-vector corpus).
- Method 2 cannot reuse that index (different embedding space). It embeds the **full corpus** via batched forward passes, extracts term-span hidden states, and ranks via in-memory cosine. Corpus embeddings are cached to `.npy` for reuse.

- **Query source**: `data/input_with_context.csv` (263 terms + patient context)
- **Corpus**: `rag_disease` SQLite table (all rows)
"""

import os, sys, argparse
os.environ['TOKENIZERS_PARALLELISM'] = 'false'
sys.path.insert(0, '.')
# NOTE: Do NOT call load_dotenv() here — model_loader.py does it internally.
# Calling load_dotenv() before the sentence-transformers/torch imports, combined
# with a prior faiss import, causes a silent threading crash on macOS.
# faiss is imported later (after model.encode) for the same reason.

import sqlite3
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

from src.utils.model_loader import get_embedding_model_cached
from src.utils.embeddings import EmbeddingAdapter
from src.KnowledgeDb.faiss_sqlite_pipeline import FAISSSQLiteSearch
import faiss  # imported after torch/ST model is initialized

"""## 0. Parse arguments"""

parser = argparse.ArgumentParser(
    description='Context embedding strategies for ontology mapping'
)
parser.add_argument('--input', '-i', required=True,
                    help='Path to input CSV (must have "term" and "context" columns)')
parser.add_argument('--model', '-m', default='pubmed-bert',
                    help='Embedding model method (default: pubmed-bert)')
parser.add_argument('--category', '-c', default='disease',
                    help='Ontology category (default: disease)')
parser.add_argument('--top-k', '-k', type=int, default=5,
                    help='Number of top matches to return (default: 5)')
parser.add_argument('--context-keys', nargs='+',
                    default=['CANCER_TYPE', 'CANCER_TYPE_DETAILED',
                             'HISTOLOGICAL_DIAGNOSIS', 'HISTOLOGICAL_SUBTYPE',
                             'ONCOTREE_CODE', 'DIAGNOSIS',
                             'ICD_O_3_HISTOLOGY', 'ICD_10'],
                    help='Context keys to extract for embedding')
parser.add_argument('--output-dir', '-o', default='data/outputs',
                    help='Output directory (default: data/outputs)')
parser.add_argument('--skip-method2', action='store_true',
                    help='Skip Method 2 (token extraction) to save time')
parser.add_argument('--skip-plots', action='store_true',
                    help='Skip plot generation')
args = parser.parse_args()

"""## 1. Load inputs"""

df_input = pd.read_csv(args.input)
print(f'Queries: {len(df_input)}')
df_input.head(3)

# Relevant context keys for mapping
DISEASE_CTX_KEYS = [k.upper() for k in args.context_keys]

def parse_context(ctx_str: str, keys: list[str]) -> str:
    """Extract relevant fields from semicolon key:value context string."""
    result = []
    for part in ctx_str.split(';'):
        part = part.strip()
        if ':' in part:
            k, _, v = part.partition(':')
            if k.strip().upper() in keys:
                result.append(f"{k.strip()}: {v.strip()}")
    return '; '.join(result) if result else ctx_str[:200]

# Preview
sample_term = df_input.iloc[0]['term']
sample_ctx  = df_input.iloc[0]['context']
print('Term:    ', sample_term)
print('Context: ', parse_context(sample_ctx, DISEASE_CTX_KEYS))

"""## 2. Load model + vector store"""

MODEL_METHOD = args.model
CATEGORY     = args.category
TOP_K        = args.top_k

raw_model = get_embedding_model_cached(MODEL_METHOD)
embedder  = EmbeddingAdapter(raw_model)
print('Model loaded:', MODEL_METHOD)

vs = FAISSSQLiteSearch(method=MODEL_METHOD, category=CATEGORY, om_strategy='rag')
print(f'FAISS index: {vs.index.ntotal} vectors')
print(f'SQLite rows: {vs.cursor.execute("SELECT COUNT(*) FROM rag_disease").fetchone()[0]}')

"""## 3. Define embedding strategies"""

def normalize(v: np.ndarray) -> np.ndarray:
    v = v.astype('float32')
    norms = np.linalg.norm(v, axis=-1, keepdims=True)
    return v / (norms + 1e-12)

def search(query_vec: np.ndarray, k: int = TOP_K) -> list[dict]:
    """Search the existing rag_disease FAISS index with a pre-built query vector."""
    q = normalize(query_vec.reshape(1, -1))
    D, I = vs.index.search(q, k)
    results = []
    for db_idx, score in zip(I[0], D[0]):
        if db_idx == -1:
            continue
        record_id = vs._ids[db_idx]
        row = vs.cursor.execute(
            'SELECT term, code FROM rag_disease WHERE id = ?', (record_id,)
        ).fetchone()
        if row:
            results.append({'term': row[0], 'code': row[1], 'score': float(score)})
    return results


# --- Strategy 0: Baseline (term only) ---
def embed_baseline(term: str, context: str) -> np.ndarray:
    return np.array(embedder.embed_query(term), dtype='float32')


# --- Strategy 1: Prompt concat (Reference.md §1) ---
# Format: "term -> relevant_context_fields"
def embed_concat(term: str, context: str) -> np.ndarray:
    ctx = parse_context(context, DISEASE_CTX_KEYS)
    prompt = f"{term} -> {ctx}"
    return np.array(embedder.embed_query(prompt), dtype='float32')


# --- Strategy 2: Hybrid average (Reference.md §3) ---
# average of embed(term) and embed(relevant_context)
def embed_hybrid(term: str, context: str) -> np.ndarray:
    ctx = parse_context(context, DISEASE_CTX_KEYS)
    v_term = np.array(embedder.embed_query(term), dtype='float32')
    v_ctx  = np.array(embedder.embed_query(ctx),  dtype='float32')
    return normalize((v_term + v_ctx) / 2)


STRATEGIES = {
    'baseline': embed_baseline,
    'method1_concat': embed_concat,
    'method3_hybrid': embed_hybrid,
}
print('Strategies defined:', list(STRATEGIES.keys()))

"""## 4. Sample comparison (5 queries)"""

SAMPLE_IDX = [0, 1, 2, 10, 50]

for idx in SAMPLE_IDX:
    row = df_input.iloc[idx]
    term, context = row['term'], row['context']
    ctx_parsed = parse_context(context, DISEASE_CTX_KEYS)
    print(f"{'='*70}")
    print(f"Query [{idx}]: {term}")
    print(f"Context:  {ctx_parsed}")
    print()
    for strat_name, embed_fn in STRATEGIES.items():
        vec = embed_fn(term, context)
        hits = search(vec)
        top = [(h['term'], f"{h['score']:.3f}") for h in hits]
        print(f"  [{strat_name}]")
        for i, (t, s) in enumerate(top, 1):
            print(f"    {i}. {t} ({s})")
        print()

"""## 5. Full run on all 263 queries"""

all_results = {strat: [] for strat in STRATEGIES}

for _, row in tqdm(df_input.iterrows(), total=len(df_input)):
    term, context = row['term'], row['context']
    for strat_name, embed_fn in STRATEGIES.items():
        vec  = embed_fn(term, context)
        hits = search(vec)
        entry = {'query': term}
        for i, h in enumerate(hits, 1):
            entry[f'match{i}']       = h['term']
            entry[f'match{i}_code']  = h['code']
            entry[f'match{i}_score'] = round(h['score'], 4)
        all_results[strat_name].append(entry)

dfs = {strat: pd.DataFrame(rows) for strat, rows in all_results.items()}
print('Done.')
for strat, df in dfs.items():
    print(f'  {strat}: {df.shape}')

"""## 6. Compare: match1 score distribution per strategy"""

if not args.skip_plots:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 4), sharey=True)
    for ax, (strat, df) in zip(axes, dfs.items()):
        scores = df['match1_score'].dropna()
        ax.hist(scores, bins=30, edgecolor='white')
        ax.set_title(strat)
        ax.set_xlabel('match1 score')
        ax.axvline(scores.mean(), color='red', linestyle='--', label=f'mean={scores.mean():.3f}')
        ax.legend()
    axes[0].set_ylabel('count')
    plt.suptitle('Match1 Score Distribution by Strategy', fontsize=13)
    plt.tight_layout()
    plot_path = os.path.join(args.output_dir, 'context_embedding_score_dist.png')
    plt.savefig(plot_path, dpi=120)
    print(f'Saved plot: {plot_path}')
    plt.show()

"""## 7. Side-by-side diff: where strategies disagree on match1"""

base  = dfs['baseline'][['query', 'match1', 'match1_score']].rename(columns={'match1': 'base_match1', 'match1_score': 'base_score'})
cat1  = dfs['method1_concat'][['query', 'match1', 'match1_score']].rename(columns={'match1': 'concat_match1', 'match1_score': 'concat_score'})
hyb   = dfs['method3_hybrid'][['query', 'match1', 'match1_score']].rename(columns={'match1': 'hybrid_match1', 'match1_score': 'hybrid_score'})

cmp = base.merge(cat1, on='query').merge(hyb, on='query')

# rows where at least two strategies give different match1
disagree = cmp[
    (cmp['base_match1'] != cmp['concat_match1']) |
    (cmp['base_match1'] != cmp['hybrid_match1'])
]
print(f'Queries where strategies disagree on match1: {len(disagree)} / {len(cmp)}')
disagree.head(20)

"""## 8. Save results"""

from datetime import datetime
ts = datetime.now().strftime('%Y%m%d_%H%M%S')

os.makedirs(args.output_dir, exist_ok=True)
for strat, df in dfs.items():
    path = os.path.join(args.output_dir, f'context_emb_{strat}_{ts}.csv')
    df.to_csv(path, index=False)
    print(f'Saved: {path}')

cmp_path = os.path.join(args.output_dir, f'context_emb_comparison_{ts}.csv')
cmp.to_csv(cmp_path, index=False)
print(f'Saved: {cmp_path}')

if args.skip_method2:
    print('\nSkipping Method 2 (--skip-method2 flag set).')
    sys.exit(0)

"""## Method 2: Contextualized Token Extraction (no FAISS)

Reference.md §2: instead of pooling the full sentence, locate the target term's token positions in the hidden states and average *only* those vectors. Because BERT is bidirectional, those token vectors are already context-aware.

**Setup**:
- Corpus: **all rows** from `rag_disease` SQLite (same coverage as FAISS index), embedded with batched forward passes
- Corpus embeddings cached to `data/outputs/corpus_m2_{model}.npy` — reloaded on subsequent runs
- Query: `f"{term} -> {parse_context(context, DISEASE_CTX_KEYS)}"` (term starts at position 0)
- Similarity: in-memory cosine (no FAISS)
"""

import torch
from transformers import AutoModel, AutoTokenizer

# Re-use the same model key already loaded above (pubmed-bert / sap-bert, etc.)
# We need the *raw* AutoModel to access last_hidden_state token-level vectors.
MODEL_KEY   = MODEL_METHOD          # 'pubmed-bert' loaded in cell-7
MODEL_NAME  = raw_model.config.name_or_path if hasattr(raw_model, 'config') else None

# If raw_model is a SentenceTransformer, extract its underlying AutoModel
if MODEL_NAME is None:
    # SentenceTransformer wraps a HuggingFace model; path is at [0].auto_model
    try:
        _st_module = raw_model._first_module()
        lm_model   = _st_module.auto_model
        tokenizer2 = AutoTokenizer.from_pretrained(_st_module.tokenizer.name_or_path, local_files_only=True)
        MODEL_NAME = _st_module.tokenizer.name_or_path
    except Exception:
        raise RuntimeError("Cannot extract underlying AutoModel from the loaded model.")
else:
    lm_model   = raw_model
    tokenizer2 = AutoTokenizer.from_pretrained(MODEL_NAME, local_files_only=True)

DEVICE_M2 = "cuda" if torch.cuda.is_available() else "cpu"
lm_model   = lm_model.to(DEVICE_M2).eval()
print(f"Method 2 model : {MODEL_NAME}  |  device: {DEVICE_M2}")

import sqlite3

# Load FULL corpus from rag_disease (all rows, same as FAISS index)
DB_PATH = os.getenv('VECTOR_DB_PATH', 'src/KnowledgeDb/vector_db.sqlite')
conn_m2 = sqlite3.connect(DB_PATH)
cur_m2  = conn_m2.cursor()
cur_m2.execute('SELECT id, term, code, context FROM rag_disease')
corpus_rows = cur_m2.fetchall()          # list of (id, term, code, context)
conn_m2.close()

corpus_meta  = [{'term': r[1], 'code': r[2]} for r in corpus_rows]
corpus_texts = [r[3] for r in corpus_rows]
corpus_terms = [r[1] for r in corpus_rows]

print(f'Loaded {len(corpus_rows)} corpus rows from {DB_PATH}')
print('Sample:')
for row in corpus_rows[:2]:
    print(f'  term={row[1]}')
    print(f'  context: {row[3][:120]}...')

MAX_LEN_M2 = 256   # truncation length for Method 2

def get_term_span_embedding(
    model, tokenizer, text: str, term: str, device: str = 'cpu'
) -> np.ndarray:
    """
    Embed `text` with `model`, then return the average of the hidden-state
    vectors at positions corresponding to `term`'s tokens.
    Falls back to the [CLS] vector when the term is not found in the text.
    """
    enc = tokenizer(
        text,
        return_tensors='pt',
        truncation=True,
        max_length=MAX_LEN_M2,
        return_offsets_mapping=True,
    )
    offset_mapping = enc.pop('offset_mapping')[0].tolist()   # (seq_len, 2)

    # Locate term's character span in the (possibly truncated) text
    term_start = text.find(term)
    term_end   = term_start + len(term) if term_start != -1 else -1

    if term_start == -1:
        term_token_idx = [0]   # fallback: CLS
    else:
        term_token_idx = [
            i for i, (s, e) in enumerate(offset_mapping)
            if e > term_start and s < term_end and e > s
        ] or [0]

    enc = {k: v.to(device) for k, v in enc.items()}
    with torch.no_grad():
        out    = model(**enc)
        hidden = out.last_hidden_state[0]   # (seq_len, dim)

    vec   = hidden[term_token_idx].mean(dim=0).cpu().numpy().astype('float32')
    norm  = np.linalg.norm(vec)
    return vec / (norm + 1e-12)


def cosine_search_m2(
    query_vec: np.ndarray, corpus_vecs: np.ndarray,
    corpus_meta: list[dict], k: int = TOP_K
) -> list[dict]:
    """Brute-force cosine similarity against a pre-built corpus matrix."""
    q  = query_vec / (np.linalg.norm(query_vec) + 1e-12)
    scores = corpus_vecs @ q          # (N,)
    top_idx = np.argsort(scores)[::-1][:k]
    return [
        {**corpus_meta[i], 'score': float(scores[i])}
        for i in top_idx
    ]

print('Helper functions defined.')

from tqdm.auto import tqdm

BATCH_SIZE_M2  = 32
CORPUS_CACHE   = os.path.join(args.output_dir, f'corpus_m2_{MODEL_METHOD}.npy')  # reuse across runs

def embed_corpus_batched(
    model, tokenizer, texts: list[str], terms: list[str],
    batch_size: int = BATCH_SIZE_M2, device: str = 'cpu'
) -> np.ndarray:
    """Batch-encode corpus; extract term-span hidden states for each entry."""
    dim  = model.config.hidden_size
    vecs = np.zeros((len(texts), dim), dtype='float32')

    for start in tqdm(range(0, len(texts), batch_size), desc='Embedding corpus (M2)'):
        batch_texts = texts[start : start + batch_size]
        batch_terms = terms[start : start + batch_size]

        enc = tokenizer(
            batch_texts,
            return_tensors='pt',
            truncation=True,
            max_length=MAX_LEN_M2,
            padding=True,
            return_offsets_mapping=True,
        )
        offset_maps = enc.pop('offset_mapping').tolist()   # (B, seq_len, 2)
        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            hidden = model(**enc).last_hidden_state   # (B, seq_len, dim)

        for j, (term, offsets) in enumerate(zip(batch_terms, offset_maps)):
            text       = batch_texts[j]
            term_start = text.find(term)
            term_end   = term_start + len(term) if term_start != -1 else -1

            if term_start == -1:
                idx = [0]
            else:
                idx = [
                    k for k, (s, e) in enumerate(offsets)
                    if e > term_start and s < term_end and e > s
                ] or [0]

            vec  = hidden[j][idx].mean(dim=0).cpu().numpy().astype('float32')
            norm = np.linalg.norm(vec)
            vecs[start + j] = vec / (norm + 1e-12)

    return vecs


# ── Build or load cached corpus embeddings ──────────────────────────────────
if os.path.exists(CORPUS_CACHE):
    corpus_vecs_m2 = np.load(CORPUS_CACHE)
    print(f'Loaded cached corpus embeddings: {corpus_vecs_m2.shape}  ({CORPUS_CACHE})')
else:
    corpus_vecs_m2 = embed_corpus_batched(
        lm_model, tokenizer2, corpus_texts, corpus_terms, device=DEVICE_M2
    )
    os.makedirs(args.output_dir, exist_ok=True)
    np.save(CORPUS_CACHE, corpus_vecs_m2)
    print(f'Saved corpus embeddings → {CORPUS_CACHE}  shape={corpus_vecs_m2.shape}')

SAMPLE_IDX_M2 = [0, 1, 2, 10, 50, 80, 100, 120, 150, 200]

print('=== Method 2 vs Baseline — sample comparison ===\n')

for idx in SAMPLE_IDX_M2:
    row       = df_input.iloc[idx]
    term      = row['term']
    context   = row['context']
    ctx_p     = parse_context(context, DISEASE_CTX_KEYS)

    # ── Method 2 query: term-span extraction from "term -> context"
    query_text_m2 = f"{term} -> {ctx_p}"
    q_vec_m2      = get_term_span_embedding(
        lm_model, tokenizer2, query_text_m2, term=term, device=DEVICE_M2
    )
    hits_m2 = cosine_search_m2(q_vec_m2, corpus_vecs_m2, corpus_meta)

    # ── Baseline query: embed term only (re-use FAISS from earlier cells)
    q_vec_base = np.array(embedder.embed_query(term), dtype='float32')
    hits_base  = search(q_vec_base)

    print(f"{'─'*65}")
    print(f"Query [{idx}]: {term}")
    print(f"Context:  {ctx_p[:100]}")
    print()
    print(f"  [Baseline (term only, full FAISS)]")
    for i, h in enumerate(hits_base, 1):
        print(f"    {i}. {h['term']}  ({h['score']:.3f})")
    print()
    print(f"  [Method 2 (term-span hidden states, corpus={len(corpus_rows)})]")
    for i, h in enumerate(hits_m2, 1):
        print(f"    {i}. {h['term']}  ({h['score']:.3f})")
    print()
